server:
  port: 8888

spring:
  application:
    name: config-server
#  profiles:     para rodar pegando as configs locais
#    active:
#      - native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hanielroanes/microservices-curso-erudio
          default-label: main
          search-paths:
            - 'config-server/greeting-service*'
            - 'config-server*'
#          username: user
#          password: pass