spring:
  application:
    name: greeting-service

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

greeting-service:
  greeting: 'Perf-test-update'
  default_value: 'Mundo'